name: mwo5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Test with Maven
        run: mvn -B clean test
#      - name: Build with Maven and run tests
#        run: mvn clean package
